### ISSUE TITLE
Windows Forms

### ISSUE THREAD

**Issue by Millennium-Heap** [Millennium-Heap/musical-mouse#1]
# Description
In the initial phase, we aim to create windows form with all the necessary elements to control the volume and frequency/pitch for our musical instrument. For this, we shall also add the NAudio package to our project.

## Sub-Feature
- NAudio Library will be used.
- The windows form will have the volume control slider.
- The windows form will have the pitch control slider.

## Examples (Optional)
![image](https://user-images.githubusercontent.com/78008633/106604595-dbf11e00-6585-11eb-894b-7d86bc70fcb3.png)

## Dependencies
NAudio package/library used.

## Milestones
- [x] Add the NAudio package.
- [x] Develop the volume control slider in the windows form.
- [x] Develop the pitch control slider in the windows form.

## Member/Members (@Github-Handle) (@Email-Id)
- Millennium Singha (@Millennium-Heap) (millenniumsingha@gmail.com)
